# .github/workflows/build-and-deploy.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Standalone Tailwind CSS CLI
        # This is the most robust method. It downloads the official pre-compiled binary.
        # It has no dependency on Node.js or npm to run.
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss
          chmod +x tailwindcss

      - name: Create output directory for compiled site
        # Using 'public' is a safe, neutral name that avoids any Jekyll conflicts.
        run: mkdir -p public/dist

      - name: Build Tailwind CSS
        # THE FIX: Explicitly pass the config file path with the -c flag.
        # This ensures Tailwind loads its configuration and default classes correctly.
        run: ./tailwindcss -c ./tailwind.config.js -i ./src/input.css -o ./public/dist/style.css --minify

      - name: Copy static assets to output directory
        # Copy all project files into the 'public' folder.
        run: |
          rsync -av --exclude 'public/' \
                    --exclude '.git/' \
                    --exclude '.github/' \
                    --exclude 'src/' \
                    --exclude 'tailwind.config.js' \
                    --exclude 'package*.json' \
                    --exclude 'node_modules/' \
                    --exclude 'tailwindcss' \
                    ./ ./public/

      - name: Create .nojekyll file
        # This explicitly tells GitHub Pages not to use Jekyll.
        run: touch ./public/.nojekyll

      - name: Upload public folder as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public' # Upload the compiled site folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # To deploy to GitHub Pages
      id-token: write   # To authenticate with GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
