# .github/workflows/build-and-deploy.yml
name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or any stable Node.js version you prefer

      - name: Initialize npm project
        # This step is crucial: it creates a package.json file
        # so npm install can correctly place tailwindcss in node_modules/.bin
        run: npm init -y

      - name: Install Tailwind CSS CLI
        run: npm install -D tailwindcss@latest

      - name: Create output directory for compiled site
        run: mkdir -p _site/dist # Create _site and a 'dist' subdirectory within it

      - name: Build Tailwind CSS
        # Output directly into the intended final path: _site/dist/style.css
        run: npx tailwindcss -i ./src/input.css -o ./_site/dist/style.css --minify

      - name: Copy static assets to output directory
        # Copy all project files into _site, excluding source/build files
        # The 'dist' folder within _site (containing style.css) will not be overwritten
        run: |
          rsync -av --exclude '_site' \
                    --exclude '.git' \
                    --exclude '.github' \
                    --exclude 'src' \
                    --exclude 'tailwind.config.js' \
                    --exclude 'package*.json' \
                    --exclude 'node_modules' \
                    ./ ./_site/

      - name: Upload _site folder as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site' # Upload the compiled site folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # To deploy to GitHub Pages
      id-token: write   # To authenticate with GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
